import type { components, paths } from "../types/api-types/index";

// Simple schema extractor
export type GetApiSchema<
    T extends SchemaKey
> = components["schemas"][T];


export const SchemaMap = {
    SignupResponse: "SignupResponse",
    SignupBody: "SignupBody",
    SocialLoginResponse: "SocialLoginResponse",
    SocialLoginBody: "SocialLoginBody",
    UploadUrlResponse: "UploadUrlResponse",
    UploadUrlBody: "UploadUrlBody",
    FeedVideosResponse: "FeedVideosResponse",
    FeedForumsResponse: "FeedForumsResponse",
    FeedNewsResponse: "FeedNewsResponse",
    FeedExercisesResponse: "FeedExercisesResponse",
    FeedCurriculumsResponse: "FeedCurriculumsResponse",
    FeedBooksResponse: "FeedBooksResponse",
    FeedBooksByLessonResponse: "FeedBooksByLessonResponse",
    FeedBooksBySubjectResponse: "FeedBooksBySubjectResponse",
    FilterBooksResponse: "FilterBooksResponse",
    FilterBooksBody: "FilterBooksBody",
    SearchVideosResponse: "SearchVideosResponse",
    SearchForumsResponse: "SearchForumsResponse",
    SearchNewsResponse: "SearchNewsResponse",
    UserProfileResponse: "UserProfileResponse",
    UserVideosResponse: "UserVideosResponse",
    UserForumsResponse: "UserForumsResponse",
    MeResponse: "MeResponse",
    MeProfileResponse: "MeProfileResponse",
    MeDashboardResponse: "MeDashboardResponse",
    MeLastAccessedResponse: "MeLastAccessedResponse",
    MeVideoHistoryResponse: "MeVideoHistoryResponse",
    MePostFeedbackResponse: "MePostFeedbackResponse",
    MePostFeedbackBody: "MePostFeedbackBody",
    MeFollowersResponse: "MeFollowersResponse",
    MeFollowingResponse: "MeFollowingResponse",
    MeFollowUserResponse: "MeFollowUserResponse",
    MeUnfollowUserResponse: "MeUnfollowUserResponse",
    MeGetMyVideosResponse: "MeGetMyVideosResponse",
    MeMyVideoItem: "MeMyVideoItem",
    MePostVideoResponse: "MePostVideoResponse",
    MePostVideoBody: "MePostVideoBody",
    MeDeleteVideoResponse: "MeDeleteVideoResponse",
    MeGetForumsResponse: "MeGetForumsResponse",
    MeForumItem: "MeForumItem",
    MePostForumResponse: "MePostForumResponse",
    MePostForumBody: "MePostForumBody",
    MeDeleteForumResponse: "MeDeleteForumResponse",
    MeLikeForumResponse: "MeLikeForumResponse",
    MePostForumCommentResponse: "MePostForumCommentResponse",
    MePostForumCommentBody: "MePostForumCommentBody",
    MeNotesResponse: "MeNotesResponse",
    MeAiGeneralTabsResponse: "MeAiGeneralTabsResponse",
    MeCreateAiGeneralTabResponse: "MeCreateAiGeneralTabResponse",
    MeCreateAiGeneralTabBody: "MeCreateAiGeneralTabBody",
    MeAiGeneralTabHistoryResponse: "MeAiGeneralTabHistoryResponse",
    MePostAiGeneralResponse: "MePostAiGeneralResponse",
    MePostAiGeneralBody: "MePostAiGeneralBody",
    MeUpdateAiGeneralTabResponse: "MeUpdateAiGeneralTabResponse",
    MeUpdateAiGeneralTabBody: "MeUpdateAiGeneralTabBody",
    MeDeleteAiGeneralTabResponse: "MeDeleteAiGeneralTabResponse",
    MeRateAiGeneralResponse: "MeRateAiGeneralResponse",
    MeRateAiGeneralBody: "MeRateAiGeneralBody",
    MeGetAiTopicsResponse: "MeGetAiTopicsResponse",
    MeAiTopicHistoryResponse: "MeAiTopicHistoryResponse",
    MeCallAiTopicResponse: "MeCallAiTopicResponse",
    MeCallAiTopicBody: "MeCallAiTopicBody",
    MeDeleteAiTopicResponse: "MeDeleteAiTopicResponse",
    MeRateAiTopicResponse: "MeRateAiTopicResponse",
    MeRateAiTopicBody: "MeRateAiTopicBody",
} as const;

export type SchemaKey = typeof SchemaMap[keyof typeof SchemaMap];
